amazonProperties:
  endpointUrl: https://s3.us-east-1.amazonaws.com 
  bucketName: ani-multipart-test1 
  longTermAccessKey: <accessk key>
  longTermSecretKey: <secret key>
  s3UploadRole: arn:aws:iam::123456789012:role/ani_s3_full_access
  s3DownloadRole: arn:aws:iam::123456789012:role/ani_s3_read_only
   
spring:
  http:
     multipart:
         maxFileSize: 200MB
         maxRequestSize: 215MB	    